### ISSUE TITLE
Why not using regex in STL?

### ISSUE THREAD

**Issue by MForever78** [BenHanson/lexertl#20]
Since regex is included in STL, why don't you use it directly?

I have this question because the regex string in STL is a little bit different with the lexertl pattern string, since it requires double "\\" to escape meta symbol. When I create patterns, I get a little bit confusing.

Is there a particular reason to avoid using regex in STL?

**Comment by BenHanson** [comment]
The Regular Expressions syntax used in lexertl has its roots in the syntax of lex and flex, with some newer features such as abstemious repeats and Unicode support added. std::regex uses NFA matching which is slower and in the Microsoft version at least is prone to the stack overflowing (http://stackoverflow.com/questions/27331047/c-std-regex-crashes-in-msvc-during-long-multiline-match/30128172). Note that in my first attempt at a lexer generator I used an array of regular expressions and tried matching one at a time and the performance was horrible.

Unfortunately due to history there are several flavours of regular expression/regex syntax out there. You will note that std::regex itself supports several flavours. Luckily you can use the double escape syntax in lexertl if you like, which will at least help you with that particular issue.

**Comment by MForever78** [comment]
Thanks for the detailed explanation!
